### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by mjpitz** [indeedeng/util#12]
To better inform followers on how to contribute to this library, lets add a CONTRIBUTING.md

**Comment by hnarasaki** [comment]
@mjpitz Would it be ok if I add the CONTRIBUTING.md from the indeedeng/cluster-preset repo https://github.com/indeedeng/cluster-preset/blob/master/CONTRIBUTING.md to this one?

**Comment by mjpitz** [comment]
@hnarasaki : sounds good. I've been meaning to draft a default one for projects to use.

**Comment by hnarasaki** [comment]
Hi @mjpitz, I'd like to do this one. Would it be possible to add the label `hacktoberfest-accepted` to this issue? No problem if not, I can still help out with this.

**Comment by mmorrisontx** [comment]
Closing all issues, as this repository is now archived.
