### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by karimocaml** [indeedeng/util#17]
I am using util/mmap from maven.
When I use : 
   ` Stat.stat(file.getAbsolutePath()).getcTime()`  

I have these following warning:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.indeed.util.mmap.Stat (file:) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of com.indeed.util.mmap.Stat
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

i use it with openjdk11.

**Comment by mmorrisontx** [comment]
Closing all issues, as this repository is now archived.
