### ISSUE TITLE
Clarify whether individual methods are threadsafe

### ISSUE THREAD

**Issue by jbellis** [indeedeng/util#47]
The blog post introducing util-mmap suggests using AtomicSharedReference for thread safety.  It looks like this is just a reference counter so that it can unmap files safely when no longer used, and that individual methods in MMapBufferReader and DirectMemory are threadsafe with no need for extra synchronization.  Is that correct?

**Comment by mmorrisontx** [comment]
Closing all issues, as this repository is now archived.
