### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by karussell** [indeedeng/util#7]
After heavy searching, asking [here](http://stackoverflow.com/questions/38293892/java-mmap-fails-on-android-with-mmap-failed-enomem-out-of-memory) and [here](http://stackoverflow.com/questions/38315292/unmapping-or-release-a-mappedbytebuffer-under-android) on SO it looks like this library might solve my problem of unmapping through a native binding - thanks :) !

Do you know if it works on (most) Android devices?

And as you see in the first question above that there seems to be a virtual memory limit on Android, are there any plans to implement kind of a mmap-cache which does mapping and unmapping under the hood? E.g. I have a 3gb file and map just 10 of the most recent accessed segments (e.g. with size of 0.1gb) and e.g. unmap the oldest automatically to be always under the ~1.3-1.5gb limit.

BTW: Some links in the readme should move to github e.g. [MMapBuffer.java](https://github.com/indeedeng/util/blob/master/mmap/src/main/java/com/indeed/util/mmap/MMapBuffer.java)?

**Comment by jpitz** [comment]
Sorry for the late response on this issue.

I'm unsure if our MMap library works on Android. Most of our use cases for that class are on the server. If you experiment around with various android devices, I'd be curious to hear if it was successful.

**Comment by mmorrisontx** [comment]
Closing all issues, as this repository is now archived.
